FROM node:22-alpine AS builder

ARG NEXT_PUBLIC_BASE_URL
ENV NEXT_PUBLIC_BASE_URL=$NEXT_PUBLIC_BASE_URL

WORKDIR /frontend


COPY package*.json .

RUN npm install 

COPY . . 

RUN npm run build

EXPOSE 3000

FROM node:22-alpine 

RUN apk add --no-cache ca-certificates

WORKDIR /frontend 

COPY package*.json .

RUN npm install --omit=dev

COPY --from=builder /frontend/next.config.ts ./
COPY --from=builder /frontend/.next/ ./.next
COPY --from=builder /frontend/node_modules ./node_modules
COPY --from=builder /frontend/public ./public




CMD ["npm","run","start"]

