import type { Metadata } from "next";
import { Poppins, Inter } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/context/authContext";
import { ToastNotificationProvider } from "@/context/toastNotificationContext";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${poppins.variable} font-body antialiased bg-bg text-text-heading   `}
      >
        <AuthContextProvider>
          <ToastNotificationProvider>{children}</ToastNotificationProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
