name: Deploy to production

on:
  push:
    branches:
      - production

jobs:
  deploy-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the backend docker image
        run: docker build -t rahuldocker974/backend_beatroom:${{ github.sha }} ./backend

      - name: Push backend docker image
        run: docker push rahuldocker974/backend_beatroom:${{ github.sha }}

      - name: Build the frontend docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} \
            -t rahuldocker974/frontend_beatroom:${{ github.sha }} \
            ./frontend

      - name: Push frontend docker image
        run: docker push rahuldocker974/frontend_beatroom:${{ github.sha }}

      - name: SSH into backend VM and start Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            else
              echo "Docker already installed. Skipping installation."
            fi

            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
            echo "CROSS_ORIGIN_URL=${{ secrets.CROSS_ORIGIN_URL }}" >> .env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
            echo "PORT=${{ secrets.PORT_BACKEND }}" >> .env
            echo "OTP_SECRET=${{ secrets.OTP_SECRET }}" >> .env
            echo "Ac_SECRET=${{ secrets.Ac_SECRET }}" >> .env
            echo "Ref_SECRET=${{ secrets.Ref_SECRET }}" >> .env
            echo "UINQUE_USERID_SECRET=${{ secrets.UINQUE_USERID_SECRET }}" >> .env
            echo "EMAIL=${{ secrets.EMAIL }}" >> .env
            echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> .env

            docker pull rahuldocker974/backend_beatroom:${{ github.sha }}
            docker stop backend || true
            docker rm backend || true

            docker run -d \
              -p 1270.0.0.1:8080:8080 \
              --name backend \
              --env-file .env \
              --restart unless-stopped \
              rahuldocker974/backend_beatroom:${{ github.sha }}

      - name: SSH into frontend VM and start Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_FRONTEND }}
          username: ${{ secrets.USERNAME_FRONTEND }}
          key: ${{ secrets.KEY_FRONTEND }}
          port: ${{ secrets.PORT_FRONTEND }}
          script: |
            if ! command -v docker &> /dev/null
            then
              echo "Docker not found. Installing..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            else
              echo "Docker already installed. Skipping installation."
            fi

            docker pull rahuldocker974/frontend_beatroom:${{ github.sha }}
            docker stop frontend || true
            docker rm frontend || true

            docker run -d \
              -p 127.0.0.1:3000:3000 \
              --name frontend \
              --restart unless-stopped \
              rahuldocker974/frontend_beatroom:${{ github.sha }}